spring:
  application:
    name: infocom-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        default_schema: infocom
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

flyway:
  schemas: infocom

server:
  port: 80

---

spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        type: trace

---

spring:
  profiles: production
  jpa:
    properties:
      hibernate:
        show_sql: false
